{% set name = "rdkit" %}
{% set version = "2019.03.1" %}
{% set filename = "Release_%s.tar.gz" % version.replace(".", "_") %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  fn:  {{ filename }}
  url: https://github.com/rdkit/rdkit/archive/{{ filename }}
  sha256: 41d0d9b82daaca8662b269096361577537fe098176c7da9cf5301c42d2f2068e
  patches:
    - vs2015.patch  # [win and py>=35]

build:
  number: 0
  skip: true  # [py27]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - jom  # [win]
  host:
    - boost
    - cairo
    - eigen
    - freetype
    - python
    - numpy
    - pillow
    - pandas
    - postgresql
  run:
    - boost
    - cairo
    - python
    - pillow
    - pandas
    - {{ pin_compatible('numpy') }}
    - pycairo
    - six

outputs:
  - name: rdkit
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - jom  # [win]
      host:
        - boost
        - cairo
        - eigen
        - freetype
        - python
        - numpy
        - pillow
        - pandas
        - postgresql
      run:
        - boost
        - cairo
        - python
        - pillow
        - pandas
        - {{ pin_compatible('numpy') }}
        - pycairo
        - six
    script: install-rdkit.sh  # [unix]
    script: install-rdkit.bat  # [win]
    test:
      imports:
        - rdkit
        - rdkit.Avalon
        - rdkit.Chem
        - rdkit.Chem.AllChem
        - rdkit.DataManip
        - rdkit.Dbase
        - rdkit.DistanceGeometry
        - rdkit.ForceField
        - rdkit.Geometry
        - rdkit.ML
        - rdkit.Numerics
        - rdkit.SimDivFilters
        - rdkit.VLib
        - rdkit.VLib.NodeLib

  - name: rdkit-postgresql
    script: install-rdkit-postgresql.sh  # [unix]
    script: install-rdkit-postgresql.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('rdkit-postgresql') }}
    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - jom  # [win]
      host:
        - {{ pin_subpackage('rdkit', exact=True) }}
        - postgresql
      run:
        - {{ pin_subpackage('rdkit', exact=True) }}
        - postgresql
    about:
      summary: The postgresql extension of RDKit

about:
  home: http://rdkit.org
  license: BSD 3-Clause
  license_file: license.txt
  summary: 'RDKit is a collection of cheminformatics and machine-learning software written in C++ and Python.'
  doc_url: http://www.rdkit.org/docs/index.html
  dev_url: https://github.com/rdkit/rdkit

extra:
  recipe-maintainers:
    - pstjohn
    - mcs07
    - bgruening
